### ISSUE TITLE
Install without AWS

### ISSUE THREAD

**Issue by tgpmoraes** [meccano-iot/servicemanager#26]
Hi,
Is it possible to install this service without the AWS subscription?

Regards,
Tiago Moraes

**Comment by rogeriobiondi** [comment]
Hello, Tiago.

Yes. It's possible installing all the components without the AWS subscription. Some plugins of service manager, such as devices:1.0 and s3_export:1.0 as specifically designed to use AWS services such as SNS and S3. But we may create other plugins with the corresponding Azure functionality. In order to disable such plugins, just follow the steps bellow:

cd /servicemanager/plugins/s3_export\:1.0

edit the plugin.json file and disable this plugin:

{
  "plugin" : "s3_export:1.0",
  "engine" : "node",
  "enabled" : false,
  "schedule" : "* 2 * * *",
  "description" : "Export data to Amazon-S3 service",
  "type" : "stream",
  "executionContext" : "master"
}


cd /servicemanager/plugins/devices\:1.0

edit the plugin.json

{
  "plugin" : "devices:1.0",
  "engine" : "node",
  "enabled" : false,
  "schedule" : "*/10 * * * *",
  "description" : "Create and send report of devices in FAIL status",
  "type" : "worker",
  "executionContext" : "master"
}

You will still need to define some void value to this variables.

export AWS_ACCESSKEYID=NONE
export AWS_SECRETACCESSKEY=NONE
export AWS_TOPICARN=NONE
export AWS_SSLENABLED=false

In the future we may change the variables above to be OPTIONAL and also add the AZURE configuration. It would be nice to write the plugins devices/s3_export for the corresponding Azure Services S3 (data storage) and SNS (sending email).

If you have any other question, please let me know.

Best regards,
Rogerio

**Comment by tgpmoraes** [comment]
Perfect Rogerio, now the installation occurred smoothed.

**Comment by rogeriobiondi** [comment]
If you have any other question, please let me know. You're welcome!

Best regards,
Rogerio
